# Generated by Django 3.0.6 on 2020-07-05 12:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.IntegerField(choices=[(0, 'Unspecified'), (1, 'Cancelled'), (2, 'Forthcoming'), (3, 'Postponed indefinitely'), (4, 'Active'), (5, 'Inactive'), (6, 'Unknown'), (7, 'deleted')], default=5)),
                ('create_time', models.DateTimeField(editable=False)),
                ('update_time', models.DateTimeField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Category')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
