# Generated by Django 3.0.6 on 2020-06-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200610_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
