# Generated by Django 3.0.8 on 2020-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='date_taken',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(),
        ),
    ]
