# Generated by Django 3.0.6 on 2020-06-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20200618_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='h_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
