# Generated by Django 3.0.6 on 2020-06-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_project_h_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='h_price',
            field=models.FloatField(default=0),
        ),
    ]
